### ISSUE TITLE
increase upload limit in WordPress

### ISSUE THREAD

**Issue by michielbdejong** [michielbdejong/snickers-applications#11]
Apparently there is a 2Mb limit for media uploads in WordPress. There also seems to be a limit on the size of plugin and theme installs (although those are downloaded, not uploaded).

@pierreozoux do you know where to adjust those limits?

**Comment by nnn-gif** [comment]
increasing wordpress limit need to be done on php configuration or .htaccess

**Comment by pierreozoux** [comment]
@niktrix :+1:

**Comment by michielbdejong** [comment]
OK, I remember the situation now, this is only done in the [Trovebox image](https://github.com/michielbdejong/snickers-applications/blob/master/src/trovebox/Dockerfile#L35), @niktrix can you move it from there to the [lamp image](https://github.com/michielbdejong/snickers-applications/blob/master/src/lamp/Dockerfile#L39), so that it also applies to WordPress and all other lamp apps?
