### ISSUE TITLE
Add Cozy

### ISSUE THREAD

**Issue by michielbdejong** [michielbdejong/snickers-applications#5]
There is a Cozy Dockerfile in https://github.com/cozy-labs/cozy-docker/ - have to see how we can adapt that to our needs.

**Comment by nnn-gif** [comment]
cozy is using python, do we need to make base python image similar to lamp image

**Comment by michielbdejong** [comment]
I think they're using nodejs, but there is no need to make a base image if the Docker image they published themselves works well. We should use the official Dockerfiles of software projects as much as possible, if they publish one.
