### ISSUE TITLE
core install command in WordPress image failing

### ISSUE THREAD

**Issue by michielbdejong** [michielbdejong/snickers-applications#8]
The [core install](https://github.com/michielbdejong/snickers-applications/blob/master/src/wordpress/install-application.sh#L26-L27) command fails with the following error:

```
Too many positional arguments: ...
```

I think this happens when you don't specify the [environment variables used by the script](https://github.com/michielbdejong/snickers-applications/blob/master/src/wordpress/install-application.sh#L15-L19) during the first run.

We should alter the script so that if not all necessary variables are defined, it halts and does not install anything. The run.sh script that calls install-application.sh should then somehow (how?) become aware the installation was not successful, and not [touch the `/init.done` file](https://github.com/michielbdejong/snickers-applications/blob/master/src/lamp/run.sh#L49-L53) in this case.

**Comment by nnn-gif** [comment]
Is there any way I can access these config.json inside Docker container, for ex ADMIN_EMAIL,ADMIN_USER in environment variables

**Comment by michielbdejong** [comment]
I just realized the `backendEnv` part of config.json is probably broken, and that may even just be what is causing this bug. Will close until I have more information.
